apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
components:
- ../../../../components/project-admin-rolebindings/apps-predictions
- ../../../../components/limitranges/default
- ../../../../components/resourcequotas/small/
namespace: apps-predictions
